repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
    - id: end-of-file-fixer
    - id: trailing-whitespace
    - id: check-yaml
- repo: https://github.com/antonbabenko/pre-commit-terraform
  rev: v1.100.0
  hooks:
    - id: terraform_fmt
    - id: terraform_tflint
    - id: terraform_validate
    - id: terraform_docs
    - id: terraform_checkov
- repo: https://github.com/TekWizely/pre-commit-golang
  rev: v1.0.0-rc.1
  hooks:
    - id: go-mod-tidy-repo
    - id: go-fmt
      files: tests/.*\.go$
    - id: go-test-mod
