name: Terraform CI

on:
  push:
    branches: ['**']  # Se ejecuta en cualquier rama
  pull_request:
    branches: ['**']  # También en pull requests

jobs:
  terraform-ci:
    name: Terraform CI Pipeline
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.13.0"

      - name: Setup TFLint
        uses: terraform-linters/setup-tflint@v4
        with:
          tflint_version: latest

      - name: Terraform fmt
        run: terraform fmt -check -recursive

      - name: TFLint
        run: |
          tflint --init
          tflint

      - name: Terraform validate
        run: |
          terraform init -backend=false
          terraform validate

      - name: Checkov
        uses: bridgecrewio/checkov-action@v12
        with:
          output_format: cli,sarif
          output_file_path: console,results.sarif
          quiet: true
          framework: terraform

      - name: Upload Checkov results
        uses: github/codeql-action/upload-sarif@v2
        if: success() || failure()
        with:
          sarif_file: results.sarif
